---
# common
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - update
    - users
    - docker
    - k8s

- hosts: k8s-master
  become: yes
  gather_facts: no
  roles:
    - k8s-master

- hosts: k8s-node1
  become: yes
  gather_facts: no
  roles:
    - k8s-node