- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
  register: join_command
- debug: msg="{{join_command.stdout}}"

- name: Copy cluster initialized to local file
  local_action: copy content="{{ join_command.stdout }}" dest="./cluster-init.txt"

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"


- name: copy admin conf for nodes
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: roles/k8s-node/files/   
    flat: yes

- name: Install calico pod network
  become: false
  command: kubectl create -f https://projectcalico.docs.tigera.io/manifests/calico.yaml

- name: Install matrics
  become: false
  command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml 

